server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3000/myDb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update